
development:
  adapter: postgresql 
  database: wellness_dev
  pool: 5
  timeout: 5000
  host: localhost
  port: 5433

test:
  adapter: postgresql 
  database: wellness_test
  pool: 5
  timeout: 5000
  host: localhost
  port: 5433

production:
  adapter: postgresql 
  database: wellness_prod
  pool: 5
  timeout: 5000
